// Types mirroring public/ion/brain-v2-payload.json — generated by
// Strategy Claude's payload script in the SpencerOS repo. Don't
// hand-edit; treat as read-only.

export type Moon = {
  ts: string;
  quote_excerpt: string;
  classification: string;
  codex_reference: string | null;
  moon_color: string;
  orbit_radius: number;
  orbit_phase: number;
  // V2.0.1 per-moon orbital plane (ion-around-nucleus visual)
  orbit_normal_phi: number;
  orbit_normal_theta: number;
  orbit_speed: number;
};

export type Planet = {
  call_id: string;
  rep_id: string | null;
  outcome: string;
  duration_min: number | null;
  demo_role: string | null;
  is_hero: boolean;
  is_gray_matter: boolean;
  gray_matter_section: string | null;
  age_days: number;
  angular_phi: number;
  angular_theta: number;
  radius: number;
  planet_size: number;
  absorption_factor: number;
  outcome_tint_color: string;
  moons: Moon[];
};

export type Tile = {
  tile_index: number;
  lat_index: number;
  lon_index: number;
  is_active: boolean;
  codex_section: string | null;
  domain: string;
  color: string;
  saturation_boost: number;
  section_data: Record<string, unknown> | null;
  // V2.0.1 — reserved (inactive) tiles render their color but skip
  // hover/click. Optional tooltip label when hovered.
  placeholder_label?: string;
};

export type Core = {
  lat_count: number;
  lon_count: number;
  core_radius: number;
  tiles: Tile[];
};

export type RadialConfig = {
  r_base: number;
  r_jitter: number;
  r_gray_matter: number;
  section_visible_cap: number;
  section_fully_absorbed_beyond: number;
  absorption_rule: string;
};

export type BrainV2Payload = {
  version: string;
  generated_at: string;
  core: Core;
  planets: Planet[];
  radial_config: RadialConfig;
  domain_colors: Record<string, string>;
  outcome_tints: Record<string, string>;
  stats: {
    calls_total: number;
    sections_lit: number;
    inactive_tiles: number;
    cherrypicks_total: number;
    presumptive_gray_matter: number;
    hero_calls: number;
    tbds_remaining: number;
    proposed_pending: number;
  };
};

// Convert spherical (theta, phi, r) → cartesian (x, y, z).
// theta = polar angle from +y axis [0..π]; phi = azimuth on xz plane [0..2π].
export function sphericalToCartesian(
  theta: number,
  phi: number,
  r: number
): [number, number, number] {
  const sinTheta = Math.sin(theta);
  return [
    r * sinTheta * Math.cos(phi),
    r * Math.cos(theta),
    r * sinTheta * Math.sin(phi),
  ];
}

// Map lat/lon indices to a unit-sphere position.
//   lat_index in [0..lat_count-1] → theta from 0 (north pole) to π (south)
//   lon_index in [0..lon_count-1] → phi   from 0 to 2π
// Returned at unit radius; scale to the actual core_radius at the call site.
export function tileToSpherical(
  latIndex: number,
  lonIndex: number,
  latCount: number,
  lonCount: number
): { theta: number; phi: number } {
  // Tile centers — shift by 0.5 so tiles sit between grid lines, not on them.
  const theta = ((latIndex + 0.5) / latCount) * Math.PI;
  const phi = ((lonIndex + 0.5) / lonCount) * Math.PI * 2;
  return { theta, phi };
}
